version: "3.8"
services:
  headless:
    image: zenika/alpine-chrome
    depends_on:
      - postgres
    volumes:
      - ~/Foundry/Protean/protean_examples/diesel_updates/pdfs:/pdfs

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - "pg_data:/var/lib/postgresql/data"

  portal:
    user: $USER_ID
    working_dir: /project/portal
    # This will be prod
    # image: mhart/alpine-node:latest
    image: node:latest
    ports:
      - 9080:9080
      - 9082:9082
    volumes:
      - "$HOME:$HOME"
      - ".:/project"
      - "/etc/passwd:/etc/passwd"
    environment:
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
    tty: true
    stdin_open: true
    command: ["bash", "run_dev_server.sh"]

  server:
    user: $USER_ID
    working_dir: /project/server
    image: rust:latest
    ports:
      - 9081:8080
    volumes:
      - ".:/project"
      - "~/.cargo:/usr/local/cargo"
      - "/etc/passwd:/etc/passwd"
    environment:
      DEBUG_COLORS: "true"
      TERM: xterm-256color
      COLORTERM: truecolor
    tty: true
    command: ["cargo", "run"]

volumes:
  pg_data:
