//! Errors that can be generated by the cache
//!
//! We rewrap all the modules errors so the end coder can catch a fully enumerated list of errors

use serde::{Deserialize, Serialize};
use thiserror::Error;

#[derive(Debug, Clone, Error, Serialize, Deserialize)]
pub enum CacheError {
  #[error("Tried to borrow a locked value for mutation")]
  BorrowError,

  #[error("There was an error attempting to convert from one type to another")]
  ConversionError,

  #[error("Lookup for an item returned no matches")]
  NotFound,

  #[error("Input item received a none for a non-optional field in a create")]
  RequiredField,

  #[error("The database connection could not be read")]
  DbReadError,

  #[error("The database connection could not be locked for writing")]
  DbWriteError,

  #[error("A group of multiple errors")]
  ErrorList(Vec<CacheError>),
}
